name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Release Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

    #   - name: Verify tag is on main
    #     run: |
    #       TAG_COMMIT=$(git rev-parse HEAD)
    #       MAIN_COMMIT=$(git rev-parse origin/main)

    #       echo "ðŸ”– Tag commit:  $TAG_COMMIT"
    #       echo "ðŸŒ¿ Main commit: $MAIN_COMMIT"

    #       if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
    #         echo "âŒ Tag is not pointing to latest main commit. Aborting release."
    #         exit 1
    #       fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t luckyprice1103/backend:${{ env.VERSION }} .
          docker push luckyprice1103/backend:${{ env.VERSION }}
